version: '3.1'

services:
  springboot:
    image: bhavyagowda/spring-boot-mongo:latest
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: springboot
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    restart: always
    
volumes:
  data: 
  data-bkp:

networks:
  default:
    external:
      name: customoverlay
